name: Update List

on:
    schedule:
        - cron: "0 9 * * *"
    workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install Dependencies
              run: npm install
            - name: Run Build & Start
              run: npm run build & npm run start
              env:
                  client_id: ${{ secrets.CLIENT_ID }}
                  user: ${{ secrets.USER }}
                  pass: ${{ secrets.PASS }}

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "[Bot] Update List"
                  commit_user_name: GitHub Actions
                  commit_user_email: actions@github.com
                  commit_author: GitHub Actions <actions@github.com>
                  skip_checkout: true
